# Usamos una imagen ligera de Java 17
FROM eclipse-temurin:17-jdk-alpine

# Definimos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo JAR que generamos en el build
COPY target/*.jar app.jar

# Exponemos el puerto que usa Render
EXPOSE 8080

# Comando para arrancar con limite de memoria para evitar el "Out of Memory"
ENTRYPOINT ["java", "-Xmx512m", "-Xms256m", "-XX:+UseSerialGC", "-jar", "app.jar"]